on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@main"

  lint:
    needs: ["build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  test:
    needs: ["lint", "build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}

  test-simulate:
    needs: ["lint", "build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-simulate.yaml@main"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}

  release-artifacts:
    needs: ["build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-release.yaml@main"
    strategy:
      matrix:
        contract-path:
          [
            "src/MultiFactor/MultiFactor",
            "src/OwnableExecutor/OwnableExecutor",
            "src/OwnableValidator/OwnableValidator",
            "src/SocialRecovery/SocialRecovery",
            "src/WebAuthnValidator/WebAuthnValidator",
          ]
    with:
      contract-path: ${{ matrix.contract-path }}
      store-artifacts: true
